spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/employee_management_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
    hikari:
      allow-pool-suspension: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        ## Hibernate Properties
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.MySQL8Dialect
        boot:
          allow_jdbc_metadata_access: false
  sql:
    init:
      mode: never

server:
  port: 9090